#!/usr/local/bin/python3
# Copyright (c) 2024 Robert Bosch GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# -*- coding: utf-8 -*


import argparse
import random
import os

from utils.generate_prompts import inference_prompts, generate_prompts_all_pairs_repeated,generate_simple_prompts
from utils.generate_images import generate_images, generate_images_accelerate

def add_train_args(parser):
# args are not fully cleaned (yet)
# Parameters for synthetic image generation
    parser.add_argument(
        "--dataset",
        type=str,
        default="imagenet",
        help="Select dataset from: imagenet, pets, cars, food, flowers, aircraft, texture",
    )
    parser.add_argument(
        "--train_class_ids",
        nargs="+",
        action="append",
        type=int,
        default=[[1000]],
        help="Class ids of the classes to be used in the training dataset. Only relevant for ImageNet. Defaults to using all 1000 classes. All other datasets use all classes automatically.",
    )
    parser.add_argument(
        "--val_class_ids",
        nargs="+",
        action="append",
        type=int,
        default=None,
        help="Class ids of the classes to be used in the validation dataset. Only relevant for ImageNet.",
    )
    parser.add_argument(
        "--train",
        type=str,
        help="The directory where the training data set is stored.",
        action="append",
    )
    # optional: CLIP filter (not used in our experiments)
    # parser.add_argument(
    #    "--CLIP_filter",
    #     default="False",
    #   help="Set to true in order to filter images by CLIP teacher model",
    #)
    parser.add_argument(
        "--teacher",
        type=str,
        default="ViT-B-32",
        help="Architecture of the teacher model, select from open_clip (used for optional CLIP filtering).",
    )
    parser.add_argument(
        "--teacher_pretrained",
        type=str,
        default="openai",
        help="Pretraining dataset of teacher (used for optional CLIP filtering).",
    )
    parser.add_argument(
        "--guidance_scale",
        type=float,
        default=0.5,
        help="Guidance scale parameter used by Stable Diffusion.",
    )
# Parameters for the prompt generation
    parser.add_argument(
        "--diverse_prompts",#default=False,
        type=str,
        help="Set this flag to use diverse prompts generated by Llama-2-7b based on the class names.",
        required=True,
    )
    parser.add_argument(
        "--generate_prompts",#default=True,
        type=str,
        help="Set this flag to generate new prompts.",
        required=True,
    )
    parser.add_argument(
        "--generate_images",#default=True,
        type=str,
        help="Set this flag to generate new images.",
        required=True,
    )
    parser.add_argument(
        "--options_per_attribute",
        type=int,
        default=2,
        help="Number of options for diverse prompts w.r.t. location, daytime, position, camera angle.",
    )
    parser.add_argument(
        "--prompts_per_class",
        type=int,
        default=None,
        help="With simple prompts and pre-defined prompts, prompts_per_class defines the number of images/prompts to generate per class.",
    )
# hardware
    parser.add_argument(
        "--devices",
        type=int,
        default=1,
        help="Number of gpus. If >1, use accelerate to generate images in distributed setup.",
    )
    return parser

def parse_args(parser):
    parser = add_train_args(parser)
    args = parser.parse_args()
    return post_parse(args)

def post_parse(args):
    """
    Use post_parse function to initialize the class(numbers) for different dataset
    """
    if args.dataset=="imagenet":
        if args.train_class_ids[0][0]==1000:
            args.train_class_ids=[[i for i in range(1000)]]
        if args.val_class_ids!=None:
            if args.val_class_ids[0][0]==1000:
                args.val_class_ids=[[i for i in range(1000)]]
        train_class_ids = [id for sublist in args.train_class_ids for id in sublist]
        args.distil_prompts = [inference_prompts(args.dataset,id) for id in train_class_ids]
    elif args.dataset=="pets":
        train_class_ids = [id for id in range(37)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    elif args.dataset=="food":
        train_class_ids = [id for id in range(101)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    elif args.dataset=="cars":
        train_class_ids = [id for id in range(196)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    elif args.dataset=="flowers":
        train_class_ids = [id for id in range(102)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    elif args.dataset=="texture":
        train_class_ids = [id for id in range(47)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    elif args.dataset=="aircraft":
        train_class_ids = [id for id in range(100)]
        args.train_class_ids = [train_class_ids]
        args.val_class_ids = [train_class_ids]
    if args.dataset!="datacomp":
        args.num_train_classes = len([id for sublist in args.train_class_ids for id in sublist])
    return args
        
if __name__ == "__main__":
    parser = argparse.ArgumentParser("Configuration")
    args = parse_args(parser)
    # Check if generate_prompts flag is set to True
    if eval(args.generate_prompts)==True:
        # Check if diverse_prompts flag is set to True
        if args.diverse_prompts=="True":
            # Generate prompts using generate_prompts_all_pairs_repeated function
            args.captions, args.n_train_images_per_class = generate_prompts_all_pairs_repeated(args.dataset,args.train_class_ids[0],args.train,args.options_per_attribute)
        else:
            if args.prompts_per_class is not None:
                # Generate prompts using generate_simple_prompts function
                args.captions = generate_simple_prompts(args.dataset,args.train_class_ids[0],args.prompts_per_class,args.train)
                args.n_train_images_per_class=args.prompts_per_class
            else:
                print("When generating simple prompts, prompts_per_class must be specified in the args")
    else:
        # if not generating prompts, load pre-defined prompts from the prompts directory
        if args.prompts_per_class is not None:
            args.n_train_images_per_class = args.prompts_per_class
        else:
            print("When generating images directly, prompts_per_class must be specified in the args")
        
        predefined_prompts=["" for x in range(len(args.train_class_ids[0])*args.prompts_per_class)]
        for index in range(len(args.train_class_ids[0])):
            for index2 in range(args.prompts_per_class):
                path = os.path.join(args.train[0], "captions", f"{args.train_class_ids[0][index]:03d}", f"{index2:03d}.txt")
                with open(path, "r") as f:
                    predefined_prompts[index*args.prompts_per_class+index2]=f.read()
        args.captions=predefined_prompts

    # Check if generate_images flag is set to True
    if eval(args.generate_images)==True:
        # Check if devices is set to 1
        if args.devices==1:
            # Generate images using generate_images function
            generate_images(args)
        else:
            # Generate images in distributed fashion
            print("Generate images in distributed fashion")
            generate_images_accelerate(args)
